name: Release

on:
  push:
    branches:
    - test

jobs:
  build:
    strategy:
      matrix:
        platform: [
          'linux-x64',
        ]
        pair: [
          'node:10',
          'node:12',
          'node:14',
        ]
        include:
          - platform: 'linux-x64'
            host-os: 'ubuntu-latest'
          - pair: 'node:10'
            language: 'node'
            version: '10'
          - pair: 'node:12'
            language: 'node'
            version: '12'
          - pair: 'node:14'
            language: 'node'
            version: '14'

    runs-on: ${{ matrix.host-os }}

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.version }}
    - name: Build adapter
      run: |
        ./build.sh "${{ matrix.platform }}" "${{ matrix.language }}" "${{ matrix.version }}"
